### ISSUE TITLE
TODO: Add information about Linux Users and Groups

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#11]
TODO: Add information about Linux Users and Groups; 

 - [x] Add information about creating, modifying, and deleting users and passwords
 - [x] Add information about use, creation, modification, and deletion of groups
 - [x] Add commands such as `adduser`, `groups`, `passwd`, etc.
 - [x] Add commands related to listing users, seeing who is logged in, etc. (`id`, `w`, `last -a`)
 - [x] add descriptions and examples

* https://github.com/zweilosec/Infosec-Notes/blob/master/linux-1/linux-basics.md#users-and-groups
