### ISSUE TITLE
TODO: Clean up description of logcheck

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#12]
TODO: Clean up description of `logcheck`
 - [ ] Description is a mass block of text. Add formatting, 
 - [ ] Put code into code blocks
 - [ ] Ensure clarity and brevity

* https://github.com/zweilosec/Infosec-Notes/blob/master/linux-1/hardening-and-setup.md#with-logcheck

**Comment by zweilosec** [comment]
Updated with logcheck info, but Continue refining this page, it needs a lot of work
