### ISSUE TITLE
TODO: Linux Enumeration - Integrate sections; add descriptions; clean up, prep for scripting

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#13]
TODO: Linux Enumeration Red Team Page

 - [ ] Integrate "Questions to Ask" into existing sections
 - [ ] Add descriptions (Keep/expand questions? Or rewrite?)
 - [ ] Clean up
 - [ ] Prep code examples for scripting
 - [ ] Split debian/redhat/BSD commands into "tabs"

* https://github.com/zweilosec/Infosec-Notes/blob/master/linux-1/linux-redteam/enumeration.md#enumeration
