### ISSUE TITLE
TODO: add argument parsing to python file sharing scripts

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#14]
TODO: add --help to python file sharing scripts

 - [ ] Add argument parsing capability
 - [ ] add `--help` argument for getting usage description
 - [ ] add arguments for all user input variables
 - [ ] FTP Server script has hardcoded values that need to be replaceable

* https://github.com/zweilosec/Infosec-Notes/blob/master/linux-1/linux-redteam/exfiltration.md#exfiltration
