### ISSUE TITLE
TODO: description, methodology, and script prep for each section in Linux Getting Access

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#15]
TODO: description, methodology, and script prep for each section

 - [ ] Add description and methodology as needed for each section
 - [ ] Prep all code examples for scripting (replace IPs and ports with variables, etc.)
 - [ ] Ensure code examples' variables are appropriate for their respective programming language

* https://github.com/zweilosec/Infosec-Notes/blob/master/linux-1/linux-redteam/getting-access.md#getting-access
