### ISSUE TITLE
TODO: Split Misc items in Wifi Hacking page into proper sections; prep code for scripting

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#16]
TODO: Split "Misc" items into proper sections; prep code for scripting

 - [ ] Put each example into its respective section
 - [ ] Clean up code examples and prep for scripting
 - [ ] Remove second "misc" section

* https://github.com/zweilosec/Infosec-Notes/blob/master/os-agnostic/wifi.md#misc
