### ISSUE TITLE
TODO: clean up steganography CTF checklist

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#17]
TODO: clean up steganography CTF checklist

 - [ ] Properly link all tools and attributions
 - [ ] Add description for what the checklist is for
 - [ ] Make sure all tools still exist
 - [ ] Check author's site for updates
 - [ ] Add "Resources" section at bottom
 - [ ] Find link for "feature for randomizing the color palette" (section 10.ii) on author's site

* https://github.com/zweilosec/Infosec-Notes/blob/master/os-agnostic/steganography.md#steganography-checklist
