### ISSUE TITLE
TODO: update and clean syntax and examples for SSH/SCP page

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#18]
TODO: update and clean syntax and examples

 - [ ] Prep code examples for scripting (as appropriate, descriptive examples may not need this)
 - [ ] Standardize variable names across examples
 - [x] Split up [SCP](https://github.com/zweilosec/Infosec-Notes/blob/master/os-agnostic/ssh-and-scp.md#scp) examples for readability
 - [ ] Move links to "[References](https://github.com/zweilosec/Infosec-Notes/blob/master/os-agnostic/ssh-and-scp.md#resources)" section or make cleaner looking if belongs
 - [ ] Expand "[Dynamic Reverse Tunnels](https://github.com/zweilosec/Infosec-Notes/blob/master/os-agnostic/ssh-and-scp.md#dynamic-reverse-tunnels)" section

* https://github.com/zweilosec/Infosec-Notes/blob/master/os-agnostic/ssh-and-scp.md#ssh--scp
