### ISSUE TITLE
TODO: Add more information about Microsoft Sysinternals

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#23]
TODO: Add more information about [Microsoft Sysinternals](https://docs.microsoft.com/en-us/sysinternals/)

 - [ ] Read about each tool and find the ones that work for Red Teaming
 - [ ] add highlights about best tools...psexec, accesschk, etc.
 - [ ] Add examples of how to use each in a command-line only environment
 - [ ] Link to relevant sections (privilege escalation, enumeration, etc.)

* https://github.com/zweilosec/Infosec-Notes/blob/master/windows-1/windows-basics.md#sysinternals
