### ISSUE TITLE
TODO: Add information about Windows "net" commands

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#24]
TODO: Add information about Windows "net" commands

 - [x] Add commands such as `net user`, `net share`, `net groups`, etc,
 - [x] Add examples and descriptions
 - [x] Unrelated: do the same for `netstat` command (since its on the same page)

* https://github.com/zweilosec/Infosec-Notes/blob/master/windows-1/windows-basics.md#cmdexe
