### ISSUE TITLE
TODO: Break PowerShell Functions up by Category; Add description of difference between cmdlets and functions

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#25]
TODO: 

 - [ ] Break PowerShell Functions section up by Category
 - [ ] Add description of difference between cmdlets and functions
 - [ ] Add information about creating functions, anonymous functions

* https://github.com/zweilosec/Infosec-Notes/blob/master/windows-1/powershell.md#functions
