### ISSUE TITLE
TODO: Expand and clean up PowerShell Bypass section.  Link to Windows Privilege Escalation page

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#27]
TODO: Expand and clean up PowerShell Bypass section.  Link to Windows Privilege Escalation page

 - [ ] Take examples from https://blog.netspi.com/15-ways-to-bypass-the-powershell-execution-policy/ and add
 - [ ] write script example of embedding PowerShell bypass in php script
 - [ ] Check the PowerShell example and see if the trailing `-` means something is missing
 - [ ] Link or add this information to Windows Privilege Escalation page

* https://github.com/zweilosec/Infosec-Notes/blob/master/windows-1/powershell.md#powershell-script-execution-bypass
