### ISSUE TITLE
Turn TODO: notes into Issue requests

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#5]
- [ ] Make an issue request for any `TODO:` items throughout notes.  This will increase visibility, and show progress made as these are closed out. 

- [ ] For all new `TODO:`'s, make an issue request at the same time.

- [ ] Tag all requests with the `TODO` label in addition to any other relevant labels.
