### ISSUE TITLE
TODO:  put commands in tables; clean and organize whole document

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#7]
TODO: 
- [ ] put commands in tables
- [ ] clean and organize whole document
- [ ] Uncategorized notes go in Misc section

* https://github.com/zweilosec/Infosec-Notes/blob/master/linux-1/linux-basics.md#linux-basics
