### ISSUE TITLE
TODO: Add more information about Linux file permissions; include descriptions and examples

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#8]
TODO: 

 - [ ] Add more information about Linux file permissions (both `octal` and `ugo` formats)
 - [ ] Add information about `chmod` and `chown` commands
 - [ ] Add descriptions and examples

* https://github.com/zweilosec/Infosec-Notes/blob/master/linux-1/linux-basics.md#file-permissions

**Comment by Cipher7** [comment]
I have initiated a pull request to fix this issue.

**Comment by zweilosec** [comment]
Hey @Cipher7 thank you for taking the time to help me out with this project! I appreciate it👍

I didn't see any pull requests when I checked the mobile app, so I'll make sure to review it when I get back to my computer.

**Comment by Cipher7** [comment]
Sure! I would love to keep contributing, just let me know if what I have written is satisfactory or if it needs any improvement.
Thank you!
