### ISSUE TITLE
TODO: add more information about Managing connections in Linux; include description and examples

### ISSUE THREAD

**Issue by zweilosec** [zweilosec/Infosec-Notes#9]
TODO: add more information about Managing connections in Linux;

 - [ ] Add commands such as telnet, SSH, nc, curl, wget
 - [ ] Add commands for listing information about open network connections: lsof -i, ss, netstat
 - [ ] include description and examples

https://github.com/zweilosec/Infosec-Notes/blob/master/linux-1/linux-basics.md#managing-connections
